update zip to 4.2.0 (#31)
The zip crate's versions 2.6.0 and 2.6.1 were yanked from crates.io:
https://github.com/zip-rs/zip2/issues/337

This is currently causing rust-analyzer to barf on Omicron while trying
to
fetch `cargo metadata`:

```
% RUSTC_BOOTSTRAP=1 /opt/rustup/toolchains/1.87.0-x86_64-unknown-linux-gnu/bin/cargo metadata --format-version 1 --manifest-path /home/rain/dev/oxide/omicron/Cargo.toml --filter-platform x86_64-unknown-linux-gnu --lockfile-path /home/rain/dev/oxide/omicron/target/rust-analyzer/metadata/workspace/Cargo.lock -Zunstable-options
<-- snip -->
error: failed to select a version for the requirement `zip = "^2.6.0"`
  version 2.6.0 is yanked
  version 2.6.1 is yanked
location searched: crates.io index
required by package `tufaceous-lib v0.1.0 (https://github.com/oxidecomputer/tufaceous?branch=main#04681f26)`
    ... which satisfies git dependency `tufaceous-lib` of package `omicron-nexus v0.1.0 (/home/rain/dev/oxide/omicron/nexus)`
    ... which satisfies path dependency `omicron-nexus` of package `omicron-omdb v0.1.0 (/home/rain/dev/oxide/omicron/dev-tools/omdb)`
```